title: George Erol Fouché | Software Engineer
description: Data Engineer & Robotics Specialist | Building innovative solutions with big data, IoT, autonomous systems, and full-stack development

# Social links
github_username: georgeerol
linkedin_username: georgefouche

# SEO Enhancement
lang: en
author: George Erol Fouché
url: https://georgeerol.github.io
baseurl: ""
google_analytics: G-L4G7PPE4VC

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
permalink: /:title/
sass:
  sass_dir: _sass
  style: compressed

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Additional metadata
keywords: "software engineer, data engineering, robotics, full-stack developer, Apache Spark, AWS, machine learning, IoT, big data"

# SEO tag settings
seo:
  name: George Erol Fouché
  type: Person

# Feed settings
feed:
  path: atom.xml
